function [metrics, energy, diagnosticMap] = analyze_5mw_gfm_diagnostics(resultFile, outputDir)
%ANALYZE_5MW_GFM_DIAGNOSTICS Build repeatable baseline diagnostics.
% This function is read-only with respect to the Simulink model. It reads a
% saved experiment result and writes compact CSV evidence into one results
% directory.

root = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(resultFile)
    resultFile = fullfile(root,'Validation_Results','liu2024_5mw_active_run.mat');
end
if nargin < 2 || isempty(outputDir)
    outputDir = fullfile(root,'Validation_Results','5MW_GFM_Characterization');
end
if ~isfolder(outputDir)
    mkdir(outputDir);
end

loaded = load(resultFile,'report','series');
assert(isfield(loaded,'report') && isfield(loaded,'series'), ...
    'Result file must contain report and series.');
r = loaded.report;
s = loaded.series;
p = Liu2024_5MW_Params();

diagTs = s.msc_diagnostic_vector;
t = diagTs.Time(:);
D = squeeze(diagTs.Data);
if size(D,1) ~= numel(t) && size(D,2) == numel(t)
    D = D.';
end
assert(size(D,2) >= 37, 'Expected at least 37 controller diagnostic channels.');

tailStart = r.tail_window_s(1);
idx = t >= tailStart;
tt = t(idx);
Dt = D(idx,:);
udc = sampleSeries(s.stage4_Udc,tt);

% C output indices are zero-based; MATLAB columns below are one-based.
gscUd = Dt(:,17);
gscUq = Dt(:,18);
gscIdRef = Dt(:,23);
gscId = Dt(:,24);
gscIqRef = Dt(:,27);
gscIq = Dt(:,30);
mscIqRef = Dt(:,31);
mscIq = Dt(:,33);
mscMod = abs(Dt(:,37));

gscVoltage = hypot(gscUd,gscUq);
gscMod = 1.5*gscVoltage./max(udc,1);
gscIRef = hypot(gscIdRef,gscIqRef);
gscI = hypot(gscId,gscIq);
gscTrackingError = hypot(gscIdRef-gscId,gscIqRef-gscIq);
mscTrackingError = abs(mscIqRef-mscIq);

metric = { ...
    'Ppcc_mean'; 'Udc_mean'; 'Ppcc_slope'; 'Udc_slope'; ...
    'omega_g_mean'; 'omega_t_mean'; 'omega_g_slope'; 'omega_t_slope'; ...
    'theta_slope'; 'torque_residual'; ...
    'gsc_modulation_max'; 'msc_modulation_max'; ...
    'gsc_current_ref_max'; 'gsc_current_max'; ...
    'msc_iq_ref_max'; 'msc_iq_max'; ...
    'gsc_tracking_error_rms'; 'gsc_tracking_error_max'; ...
    'msc_tracking_error_rms'; 'msc_tracking_error_max'; ...
    'gsc_modulation_limit_duty'; 'gsc_current_ref_limit_duty'; ...
    'msc_current_ref_limit_duty'};
value = [ ...
    r.ppcc_mean_W; r.udc_mean_V; r.ppcc_slope_Wps; r.udc_slope_Vps; ...
    r.omega_g_mean_radps; r.omega_t_mean_radps; ...
    r.omega_g_slope_radps2; r.omega_t_slope_radps2; ...
    r.theta_slope_radps; r.torque_residual_pu; ...
    max(gscMod); max(mscMod); max(gscIRef); max(gscI); ...
    max(abs(mscIqRef)); max(abs(mscIq)); ...
    rms(gscTrackingError); max(gscTrackingError); ...
    rms(mscTrackingError); max(mscTrackingError); ...
    mean(gscMod >= 0.995*p.gsc_modulation_limit); ...
    mean(gscIRef >= 0.995*p.gsc_current_vector_limit); ...
    mean(abs(mscIqRef) >= 0.995*p.motor_current_limit)];
unit = { ...
    'W'; 'V'; 'W/s'; 'V/s'; 'rad/s'; 'rad/s'; 'rad/s^2'; 'rad/s^2'; ...
    'rad/s'; 'pu'; 'pu'; 'pu'; 'A'; 'A'; 'A'; 'A'; 'A'; 'A'; 'A'; 'A'; ...
    'fraction'; 'fraction'; 'fraction'};
limit = [ ...
    p.P_wt_rated*0.01; p.Vdc*0.02; 5e3; 5; NaN; NaN; 0.01; 0.01; ...
    5e-4; 0.01; p.gsc_modulation_limit; 0.90; ...
    p.gsc_current_vector_limit; p.grid_current_limit; ...
    p.motor_current_limit; p.motor_current_limit; ...
    NaN; NaN; NaN; NaN; 0; 0; 0];
criterion = { ...
    'absolute error from 5 MW'; 'absolute error from 1500 V'; ...
    'absolute value'; 'absolute value'; 'record'; 'record'; ...
    'absolute value'; 'absolute value'; 'absolute value'; 'absolute value'; ...
    'less than'; 'less than'; 'less than or equal'; 'less than or equal'; ...
    'less than or equal'; 'less than or equal'; 'record'; 'record'; ...
    'record'; 'record'; 'equal zero'; 'equal zero'; 'equal zero'};
pass = nan(size(value));
pass(1) = abs(value(1)-p.P_wt_rated) < limit(1);
pass(2) = abs(value(2)-p.Vdc) < limit(2);
pass(3:4) = abs(value(3:4)) < limit(3:4);
pass(7:10) = abs(value(7:10)) < limit(7:10);
pass(11:12) = value(11:12) < limit(11:12);
pass(13:16) = value(13:16) <= limit(13:16);
pass(21:23) = value(21:23) == 0;
metrics = table(metric,value,unit,criterion,limit,pass);
writetable(metrics,fullfile(outputDir,'baseline_regression.csv'));

% Mechanical and DC-link energy accounting over the same tail window.
omegaT = sampleSeries(s.tm_omega_t,tt);
omegaG = sampleSeries(s.tm_omega_g,tt);
theta = sampleSeries(s.tm_theta_tw,tt);
te = sampleSeries(s.tm_T_e,tt);
taero = sampleSeries(s.stage4_Taero_effective,tt);
paeroRaw = sampleSeries(s.wind_Paero,tt);
ppcc = sampleSeries(s.stage4_Ppcc,tt);

pAeroEffective = taero.*omegaT;
pElectromagnetic = -te.*omegaG;
pMechanicalDamping = p.D_t*omegaT.^2 + p.D_g*omegaG.^2 + ...
    p.D_sh*(omegaT-omegaG).^2;
eMechanical = 0.5*p.J_t*omegaT.^2 + 0.5*p.J_g*omegaG.^2 + ...
    0.5*p.K_sh*theta.^2;
eDc = 0.5*p.Cdc*udc.^2;
dMechanicalEnergy = signalSlope(tt,eMechanical);
dDcEnergy = signalSlope(tt,eDc);

energyMetric = { ...
    'Paero_raw_mean'; 'Paero_effective_mean'; 'P_electromagnetic_mean'; ...
    'Ppcc_mean'; 'mechanical_damping_loss_mean'; ...
    'dE_mechanical_dt'; 'dE_dc_dt'; ...
    'mechanical_balance_residual'; 'electromagnetic_to_grid_gap'};
energyValue = [ ...
    mean(paeroRaw); mean(pAeroEffective); mean(pElectromagnetic); ...
    mean(ppcc); mean(pMechanicalDamping); dMechanicalEnergy; dDcEnergy; ...
    mean(pAeroEffective)-mean(pElectromagnetic)-mean(pMechanicalDamping)-dMechanicalEnergy; ...
    mean(pElectromagnetic)-mean(ppcc)-dDcEnergy];
energyUnit = repmat({'W'},size(energyMetric));
energy = table(energyMetric,energyValue,energyUnit);
writetable(energy,fullfile(outputDir,'energy_balance.csv'));

diagnosticMap = table((1:37).', { ...
    'GSC_gate_1';'GSC_gate_2';'GSC_gate_3';'GSC_gate_4';'GSC_gate_5';'GSC_gate_6'; ...
    'MSC_gate_1';'MSC_gate_2';'MSC_gate_3';'MSC_gate_4';'MSC_gate_5';'MSC_gate_6'; ...
    'P_ref';'P_pcc';'VSG_w_ref';'VSG_theta_ref';'GSC_Ud_ref';'GSC_Uq_ref'; ...
    'Q_pcc';'voltage_ref';'Uod_ref';'PCC_ud';'GSC_Id_ref';'GSC_Id'; ...
    'Uoq_ref';'PCC_uq';'GSC_Iq_ref';'PLL_grid_angle';'Pre_syn';'GSC_Iq'; ...
    'MSC_Iq_ref';'DVC_output';'MSC_Iq';'MSC_Ud_ref';'MSC_Uq_ref'; ...
    'MSC_voltage_magnitude';'MSC_modulation'}, ...
    'VariableNames',{'column','signal'});
writetable(diagnosticMap,fullfile(outputDir,'diagnostic_map.csv'));

fprintf(['5 MW diagnostics: GSC mod %.4f, MSC mod %.4f, ' ...
    'GSC limit duty %.4g, MSC limit duty %.4g.\n'], ...
    max(gscMod),max(mscMod),value(21),value(23));
end

function y = sampleSeries(ts,t)
sourceT = ts.Time(:);
sourceY = squeeze(ts.Data);
sourceY = sourceY(:);
[sourceT,uniqueIndex] = unique(sourceT,'stable');
sourceY = sourceY(uniqueIndex);
y = interp1(sourceT,sourceY,t,'linear','extrap');
end

function value = signalSlope(t,y)
fitValue = polyfit(t-t(1),y,1);
value = fitValue(1);
end
