function T = build_wt_parameters_from_simulink()
% Build wind-turbine same-object table from Simulink-backed variables.
% Mechanical-side source of truth: Grid_Forming_PMSG + GFM_MWT_Nonlinear_Params.

rootDir = fileparts(mfilename('fullpath'));
old = pwd;
cleanup = onCleanup(@() cd(old)); %#ok<NASGU>
cd(rootDir);

ssmMat = locate_ssm_parameters_mat();
ssm = load(ssmMat);
run(fullfile(rootDir, 'GFM_MWT_Nonlinear_Params.m'));
load_system('Grid_Forming_PMSG');

sim = struct();
sim.omega_m0 = localEvalBase('omega_m0');
sim.v_w0 = localEvalBase('v_w0');
sim.theta_tw0 = localEvalBase('theta_tw0');
sim.J_t = localEvalBase('J_t');
sim.J_g = localEvalBase('J_g');
sim.K_sh = localEvalBase('K_sh');
sim.D_sh = localEvalBase('D_sh');
sim.D_t = localEvalBase('D_t');
sim.D_g = localEvalBase('D_g');
sim.D_aero = localEvalBase('D_aero');
sim.K_v_aero = localEvalBase('K_v_aero');
sim.T_aero0 = localEvalBase('T_aero0');

names = { ...
    'omega_g0/omega_m0', ...
    'v_w0', ...
    'theta_tw0', ...
    'J_t', ...
    'J_g', ...
    'K_sh', ...
    'D_sh', ...
    'D_t', ...
    'D_g', ...
    'D_aero', ...
    'K_v_aero', ...
    'T_aero0' ...
    };

ssmVals = [ ...
    getf(ssm,'omega_g0',NaN), ...
    getf(ssm,'v_w0',NaN), ...
    getf(ssm,'theta_tw0',NaN), ...
    getf(ssm,'J_t',NaN), ...
    getf(ssm,'J_g',NaN), ...
    getf(ssm,'K_sh',NaN), ...
    getf(ssm,'D_sh',NaN), ...
    getf(ssm,'D_t',NaN), ...
    getf(ssm,'D_g',NaN), ...
    getf(ssm,'D_aero',NaN), ...
    getf(ssm,'K_v_aero',NaN), ...
    getf(ssm,'T_aero0',NaN) ...
    ]';

simVals = [ ...
    sim.omega_m0, ...
    sim.v_w0, ...
    sim.theta_tw0, ...
    sim.J_t, ...
    sim.J_g, ...
    sim.K_sh, ...
    sim.D_sh, ...
    sim.D_t, ...
    sim.D_g, ...
    sim.D_aero, ...
    sim.K_v_aero, ...
    sim.T_aero0 ...
    ]';

ratio = simVals ./ ssmVals;
ratio(~isfinite(ratio)) = NaN;

T = table(names', ssmVals, simVals, ratio, 'VariableNames', ...
    {'Parameter', 'SmallSignalValue', 'SimulinkWindTwoMassValue', 'SimulinkOverSmallSignal'});

outDir = fullfile(rootDir, 'Validation_Results');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end
writetable(T, fullfile(outDir, 'same_object_wt_from_simulink.csv'));

md = fullfile(outDir, 'same_object_wt_from_simulink.md');
fid = fopen(md, 'w');
fprintf(fid, '# 同一对象参数表（风机机械侧，以 Simulink 为准）\n\n');
fprintf(fid, '- Simulink model: `Grid_Forming_PMSG.mdl`\n');
fprintf(fid, '- Subsystem: `Wind_TwoMass`\n');
fprintf(fid, '- Small-signal source: `%s`\n\n', ssmMat);
fprintf(fid, '| Parameter | Small-signal | Simulink | Ratio (sim/ss) |\n');
fprintf(fid, '|---|---:|---:|---:|\n');
for i = 1:height(T)
    fprintf(fid, '| %s | %.9g | %.9g | %.9g |\n', ...
        T.Parameter{i}, T.SmallSignalValue(i), T.SimulinkWindTwoMassValue(i), T.SimulinkOverSmallSignal(i));
end
fclose(fid);

disp(T);
fprintf('Saved: %s\n', fullfile(outDir, 'same_object_wt_from_simulink.csv'));
fprintf('Saved: %s\n', md);
end

function v = localEvalBase(varName)
try
    v = evalin('base', varName);
catch
    v = NaN;
end
end

function v = getf(s, name, fallback)
if isfield(s, name)
    v = s.(name);
else
    v = fallback;
end
end
