function diag = run_vsg_initial_state_candidate(varargin)
%RUN_VSG_INITIAL_STATE_CANDIDATE Generate a warm-start snapshot for the VSG model.
%  The snapshot is tied to Grid_FormingVSG_PMSG.mdl and the current VSG
%  controller parameters. Do not reuse it for the legacy Grid_Forming_PMSG.

cfg = struct( ...
    'StopTime', 6.0, ...
    'H', 250, ...
    'Mp', 1.5707963e-6, ...
    'FF', 0.000225, ...
    'DvcType', 3, ...
    'MotorKp', 0.050, ...
    'MotorKi', 0.00035, ...
    'MotorKc', 0.00001, ...
    'MotorVoltLimit', 800, ...
    'MotorCurrentKp', [], ...
    'MotorCurrentKi', [], ...
    'MotorCurrentKc', [], ...
    'RunCompile', true, ...
    'InitialStateFile', '', ...
    'Pref_W', 1e6, ...
    'Qref_var', 0, ...
    'VacRef_V', 563, ...
    'VdcRef_V', 1000, ...
    'OutputTag', '', ...
    'PublishDefault', false);

if nargin == 1 && isnumeric(varargin{1})
    cfg.StopTime = varargin{1};
else
    if mod(nargin, 2) ~= 0
        error('Use either run_vsg_initial_state_candidate(StopTime) or name-value pairs.');
    end
    for k = 1:2:nargin
        name = varargin{k};
        if ~isfield(cfg, name)
            error('Unknown option: %s', name);
        end
        cfg.(name) = varargin{k + 1};
    end
end

root = fileparts(mfilename('fullpath'));
oldDir = pwd;
cleanupObj = onCleanup(@() cd(oldDir)); %#ok<NASGU>
cd(root);

if cfg.RunCompile || exist(fullfile(root, ['main_vsg.' mexext]), 'file') ~= 3
    compile_vsg_sfunction( ...
        'VSG_H', cfg.H, ...
        'VSG_MP', cfg.Mp, ...
        'MotorFF', cfg.FF, ...
        'DvcType', cfg.DvcType, ...
        'MotorKp', cfg.MotorKp, ...
        'MotorKi', cfg.MotorKi, ...
        'MotorKc', cfg.MotorKc, ...
        'MotorVoltLimit', cfg.MotorVoltLimit, ...
        'MotorCurrentKp', cfg.MotorCurrentKp, ...
        'MotorCurrentKi', cfg.MotorCurrentKi, ...
        'MotorCurrentKc', cfg.MotorCurrentKc);
end

overrides = struct( ...
    'ModelName', 'Grid_FormingVSG_PMSG', ...
    'VdcRef_V', cfg.VdcRef_V, ...
    'VacRef_V', cfg.VacRef_V, ...
    'Pref_W', cfg.Pref_W, ...
    'Qref_var', cfg.Qref_var, ...
    'SkipMexCompile', true, ...
    'UseNumericSfunParams', true, ...
    'SaveFinalState', true, ...
    'SaveOperatingPoint', true, ...
    'FinalStateName', 'xInitial', ...
    'SaveSeries', true, ...
    'SeriesMaxPoints', 60000, ...
    'ThreePhaseTail_s', 0.2);

if ~isempty(cfg.InitialStateFile)
    overrides.InitialStateFile = cfg.InitialStateFile;
    overrides.InitialStateVar = 'xInitial';
end

diag = run_no_disturbance_diagnosis(false, cfg.StopTime, 0.0, overrides);

outDir = fullfile(root, 'Validation_Results', 'Initial_State');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

if isempty(cfg.OutputTag)
    cfg.OutputTag = sprintf('DvcType%d_Kp%g_Ki%g_FF%g_%gs', ...
        cfg.DvcType, cfg.MotorKp, cfg.MotorKi, cfg.FF, cfg.StopTime);
end
outputTag = regexprep(char(cfg.OutputTag), '[^A-Za-z0-9_]+', '_');

save(fullfile(outDir, ['Grid_FormingVSG_PMSG_Init_' outputTag '_diag.mat']), 'diag', '-v7.3');
if ~isfield(diag, 'final_state') || isempty(diag.final_state)
    error('Final state was not captured.');
end

xInitial = diag.final_state; %#ok<NASGU>
candidateFile = fullfile(outDir, ['Grid_FormingVSG_PMSG_Init_' outputTag '.mat']);
save(candidateFile, 'xInitial', 'diag', '-v7.3');

metadata = struct();
metadata.model = 'Grid_FormingVSG_PMSG';
metadata.vdc_reference_V = cfg.VdcRef_V;
metadata.vac_reference_V = cfg.VacRef_V;
metadata.pref_W = cfg.Pref_W;
metadata.qref_var = cfg.Qref_var;
metadata.source_stop_time_s = cfg.StopTime;
metadata.dvc_type = cfg.DvcType;
metadata.motor_kp = cfg.MotorKp;
metadata.motor_ki = cfg.MotorKi;
metadata.motor_kc = cfg.MotorKc;
metadata.motor_volt_limit_V = cfg.MotorVoltLimit;
metadata.motor_current_kp = cfg.MotorCurrentKp;
metadata.motor_current_ki = cfg.MotorCurrentKi;
metadata.motor_current_kc = cfg.MotorCurrentKc;
metadata.motor_ff_A_per_W = cfg.FF;
metadata.vsg_H = cfg.H;
metadata.vsg_Mp = cfg.Mp;
save(candidateFile, 'xInitial', 'diag', 'metadata', '-v7.3');

officialFile = fullfile(outDir, 'Grid_FormingVSG_PMSG_Init.mat');
if cfg.PublishDefault && diag.baseline_operational_flag && diag.dc_bounded_flag && diag.power_reached_1MW_flag
    save(officialFile, 'xInitial', 'diag', 'metadata', '-v7.3');
    fprintf('Published VSG warm-start initial state: %s\n', officialFile);
else
    fprintf('Candidate retained without publishing default: %s\n', candidateFile);
end

fprintf('\n=== VSG initial-state candidate ===\n');
fprintf('source_stop_time      = %.3f s\n', cfg.StopTime);
fprintf('DvcType / Kp / Ki / Kc = %d / %.9g / %.9g / %.9g\n', cfg.DvcType, cfg.MotorKp, cfg.MotorKi, cfg.MotorKc);
fprintf('baseline_operational = %d\n', diag.baseline_operational_flag);
fprintf('power_reached_1MW    = %d\n', diag.power_reached_1MW_flag);
fprintf('dc_bounded           = %d\n', diag.dc_bounded_flag);
fprintf('dc_settled           = %d\n', diag.dc_settled_flag);
fprintf('mech_settled         = %d\n', diag.mech_settled_flag);
fprintf('Ppcc_end_mean        = %.3f kW\n', diag.Ppcc_end_mean / 1e3);
fprintf('Ppcc_target_error    = %.6f pu\n', diag.Ppcc_target_error_pu);
fprintf('Udc_end_mean         = %.3f V\n', diag.udc_end_mean);
fprintf('Udc_end_slope        = %.6f V/s\n', diag.udc_end_slope);
fprintf('Saved candidate: %s\n', candidateFile);
end
