function row = run_msc_dc_tuning_case(vLoopBw, speedKp, speedKi, simStop, vdcRef)
% Run and persist one MSC DC-link tuning candidate for the aligned GFM model.
% The selected header values remain active after the run for easy validation.

if nargin < 4
    simStop = 4.0;
end
if nargin < 5
    vdcRef = 1200;
end

root = fileparts(mfilename('fullpath'));
old = pwd;
cleanup = onCleanup(@() cd(old)); %#ok<NASGU>
cd(root);

patch_motor_header(fullfile(root, 'motorcontrol.h'), vLoopBw, speedKp, speedKi);
compile_mex(root);

diag = run_no_disturbance_diagnosis(false, simStop, 0.0, struct( ...
    'VdcRef_V', vdcRef, ...
    'VacRef_V', 563, ...
    'Pref_W', 1e6, ...
    'Qref_var', 0, ...
    'SkipMexCompile', true, ...
    'UseNumericSfunParams', true, ...
    'SaveSeries', true));

udcPp = local_tail_peak_to_peak(diag.series.udc_meas, 1.0);
tshPp = local_tail_peak_to_peak(diag.series.T_sh, 1.0);

row = table(datetime('now'), simStop, vdcRef, vLoopBw, speedKp, speedKi, ...
    diag.Ppcc_end_mean, diag.Ppcc_target_error_pu, ...
    diag.udc_end_mean, diag.udc_end_slope, udcPp, ...
    diag.omega_g_end_slope, diag.omega_t_end_slope, ...
    diag.theta_tw_end_slope, diag.T_sh_end_slope, tshPp, ...
    diag.torque_balance_Taero_Te_err_pu, ...
    double(diag.power_reached_1MW_flag), ...
    double(diag.dc_settled_flag), ...
    double(diag.mech_settled_flag), ...
    double(diag.baseline_operational_flag), ...
    'VariableNames', { ...
    'timestamp','simStop','VdcRef_V','V_LOOP_BW','SPD_KP','SPD_KI', ...
    'Ppcc_mean','Ppcc_err_pu','Udc_mean','Udc_slope','Udc_pp', ...
    'omega_g_slope','omega_t_slope','theta_tw_slope','T_sh_slope','T_sh_pp', ...
    'TaeroTe_err_pu','flag_1MW','flag_dc_settled','flag_mech_settled','flag_baseline_operational'});

row.score = abs(row.Ppcc_err_pu)/0.05 + ...
    abs(row.Udc_slope)/5 + row.Udc_pp/120 + ...
    abs(row.omega_g_slope)/1e-2 + ...
    abs(row.omega_t_slope)/1e-2 + ...
    abs(row.theta_tw_slope)/5e-4 + ...
    abs(row.T_sh_slope)/1e4 + row.T_sh_pp/1e5;

outDir = fullfile(root, 'Validation_Results');
if ~exist(outDir, 'dir'), mkdir(outDir); end
outPath = fullfile(outDir, 'msc_dc_tuning_cases_1200V.csv');
if exist(outPath, 'file')
    oldRows = readtable(outPath);
    rows = [oldRows; row]; %#ok<AGROW>
else
    rows = row;
end
writetable(rows, outPath);

disp(row);
fprintf('Saved: %s\n', outPath);
end

function patch_motor_header(hdrPath, vLoopBw, speedKp, speedKi)
txt = fileread(hdrPath);
txt = regexprep(txt, '#define\s+V_LOOP_BANDWITH\s+[0-9\.eE\+\-]+[^\r\n]*', ...
    sprintf('#define   V_LOOP_BANDWITH                     %.8g   // Hz, MSC DC-link loop', vLoopBw), 'once');
txt = regexprep(txt, '#define\s+MOTOR_PWM_SPEED_KP\s+[0-9\.eE\+\-]+', ...
    sprintf('#define   MOTOR_PWM_SPEED_KP                   %.8g', speedKp), 'once');
txt = regexprep(txt, '#define\s+MOTOR_PWM_SPEED_KI\s+[0-9\.eE\+\-]+', ...
    sprintf('#define   MOTOR_PWM_SPEED_KI                   %.8g', speedKi), 'once');
fid = fopen(hdrPath, 'w');
fwrite(fid, txt);
fclose(fid);
end

function compile_mex(root)
setenv('MW_MINGW64_LOC', 'C:\mingw64');
evalin('base', 'clear mex');
evalin('base', 'bdclose(''all'')');
evalin('base', sprintf( ...
    'cd(''%s''); mex main.c svpwm.c motorcontrol.c grid_forming_control.c;', ...
    strrep(root, '\', '\\')));
end

function pp = local_tail_peak_to_peak(s, tailSec)
t = s.t(:);
y = s.y(:);
idx = t >= t(end) - tailSec;
if nnz(idx) < 2
    pp = NaN;
else
    pp = max(y(idx)) - min(y(idx));
end
end
