function summary = run_vsg_margin_tuning_scan_20260612(varargin)
%RUN_VSG_MARGIN_TUNING_SCAN_20260612 Scan non-structural parameters for VSG-MWT.
%
% 目的：
%   当前无扰动候选工况中 MSC q 轴电流环 PI 输出长期卡在限幅
%   MscIqPiMax=MotorVoltLimit。该脚本只改变控制参数和限幅，不改拓扑结构，
%   用于判断能否降低 DC 漂移和机械扭矩斜率。
%
% 使用示例：
%   summary = run_vsg_margin_tuning_scan_20260612('MaxCases',2,'NumSegments',2);

root = fileparts(mfilename('fullpath'));
oldDir = pwd;
cleanupObj = onCleanup(@() cd(oldDir)); %#ok<NASGU>
cd(root);

p = inputParser;
addParameter(p, 'MaxCases', inf);
addParameter(p, 'StartCase', 1);
addParameter(p, 'NumSegments', 3);
addParameter(p, 'SegmentTime', 1.0);
addParameter(p, 'InitialStateFile', fullfile(root, 'Validation_Results', 'Initial_State', ...
    'Grid_FormingVSG_PMSG_Init_ContinueFrom20s_Vlim280_FF225_Kp0055_Ki00036_20260612_Segment_05.mat'));
parse(p, varargin{:});
cfg = p.Results;

if exist(cfg.InitialStateFile, 'file') ~= 2
    error('Initial state file not found: %s', cfg.InitialStateFile);
end

cases = local_cases();
startCase = max(1, cfg.StartCase);
endCase = min(numel(cases), startCase + cfg.MaxCases - 1);
summary = table();

for k = startCase:endCase
    c = cases(k);
    fprintf('\n=== VSG margin scan case %d/%d: %s ===\n', k, numel(cases), c.Tag);

    rows = run_vsg_operating_point_segments( ...
        'Tag', c.Tag, ...
        'SegmentTime', cfg.SegmentTime, ...
        'NumSegments', cfg.NumSegments, ...
        'InitialStateFile', cfg.InitialStateFile, ...
        'RunCompile', true, ...
        'DvcType', 3, ...
        'H', 250, ...
        'Mp', 1.5707963e-6, ...
        'MotorFF', c.MotorFF, ...
        'MotorKp', c.MotorKp, ...
        'MotorKi', c.MotorKi, ...
        'MotorKc', 1e-5, ...
        'MotorVoltLimit', c.MotorVoltLimit, ...
        'MotorCurrentKp', c.MotorCurrentKp, ...
        'MotorCurrentKi', c.MotorCurrentKi, ...
        'PowerLpfCutoff', 40, ...
        'PrefRampSlope', 5e5, ...
        'DcCapF', 0.03, ...
        'MotorLd', 1.02e-3, ...
        'MotorLq', 1.02e-3, ...
        'Pref_W', 1.0e6, ...
        'Qref_var', 0, ...
        'VacRef_V', 563, ...
        'VdcRef_V', 1000);

    last = rows(end,:);
    margin = c.MotorVoltLimit - last.MscIqPiMax;
    score = abs(last.Perr_pu) ...
        + abs(last.UdcSlope) / 20 ...
        + max(0, 900 - last.UdcMin) / 1000 ...
        + max(0, last.UdcMax - 1300) / 1000 ...
        + abs(last.OmegaGSlope) * 2 ...
        + abs(last.OmegaTSlope) * 2 ...
        + abs(last.TshSlope) / 1e6 ...
        + max(0, -margin) / 100;

    one = table(string(c.Tag), c.MotorVoltLimit, c.MotorCurrentKp, c.MotorCurrentKi, ...
        c.MotorFF, c.MotorKp, c.MotorKi, last.Segment, last.Ppcc_kW, last.Perr_pu, ...
        last.Udc_V, last.UdcSlope, last.UdcMin, last.UdcMax, last.TshSlope, ...
        last.OmegaGSlope, last.OmegaTSlope, last.MscIqPiMax, last.MscVcmdMax, ...
        local_optional(last, 'MscLinearVoltageLimit'), local_optional(last, 'MscModDepthMean'), ...
        local_optional(last, 'MscModDepthMax'), margin, ...
        last.Operational, last.DcSettled, last.MechSettled, score, ...
        string(last.StateFile), ...
        'VariableNames', {'Tag','MotorVoltLimit','MotorCurrentKp','MotorCurrentKi', ...
        'MotorFF','MotorKp','MotorKi','FinalSegment','Ppcc_kW','Perr_pu', ...
        'Udc_V','UdcSlope','UdcMin','UdcMax','TshSlope', ...
        'OmegaGSlope','OmegaTSlope','MscIqPiMax','MscVcmdMax', ...
        'MscLinearVoltageLimit','MscModDepthMean','MscModDepthMax','MscIqPiMargin', ...
        'Operational','DcSettled','MechSettled','Score','StateFile'});
    summary = [summary; one]; %#ok<AGROW>
end

outPath = fullfile(root, 'Validation_Results', 'vsg_margin_tuning_scan_20260612.csv');
if exist(outPath, 'file') == 2
    old = readtable(outPath);
    old = local_align_table(old, summary);
    summary = [old; summary]; %#ok<AGROW>
    [~, keep] = unique(summary.Tag, 'last');
    summary = summary(sort(keep), :);
end
writetable(summary, outPath);
fprintf('\nSaved margin tuning scan summary: %s\n', outPath);
disp(sortrows(summary, 'Score'));
end

function cases = local_cases()
cases = struct( ...
    'Tag', {}, 'MotorVoltLimit', {}, 'MotorCurrentKp', {}, 'MotorCurrentKi', {}, ...
    'MotorFF', {}, 'MotorKp', {}, 'MotorKi', {});

cases(end+1) = struct( ...
    'Tag', 'Margin_Vlim300_DefaultInner', ...
    'MotorVoltLimit', 300, ...
    'MotorCurrentKp', 1.4, ...
    'MotorCurrentKi', 0.00290476, ...
    'MotorFF', 0.000225, ...
    'MotorKp', 0.055, ...
    'MotorKi', 0.00036);

cases(end+1) = struct( ...
    'Tag', 'Margin_Vlim320_DefaultInner', ...
    'MotorVoltLimit', 320, ...
    'MotorCurrentKp', 1.4, ...
    'MotorCurrentKi', 0.00290476, ...
    'MotorFF', 0.000225, ...
    'MotorKp', 0.055, ...
    'MotorKi', 0.00036);

cases(end+1) = struct( ...
    'Tag', 'Margin_Vlim300_SofterInner', ...
    'MotorVoltLimit', 300, ...
    'MotorCurrentKp', 1.0, ...
    'MotorCurrentKi', 0.0018, ...
    'MotorFF', 0.000225, ...
    'MotorKp', 0.055, ...
    'MotorKi', 0.00036);

cases(end+1) = struct( ...
    'Tag', 'Margin_Vlim300_SofterDVC', ...
    'MotorVoltLimit', 300, ...
    'MotorCurrentKp', 1.4, ...
    'MotorCurrentKi', 0.00290476, ...
    'MotorFF', 0.000215, ...
    'MotorKp', 0.050, ...
    'MotorKi', 0.00032);
end

function value = local_optional(row, name)
if ismember(name, row.Properties.VariableNames)
    value = row.(name);
else
    value = NaN;
end
end

function old = local_align_table(old, row)
targetNames = row.Properties.VariableNames;
for k = 1:numel(targetNames)
    name = targetNames{k};
    if ~ismember(name, old.Properties.VariableNames)
        old.(name) = local_missing_column(row.(name), height(old));
    end
end
old = old(:, targetNames);
end

function values = local_missing_column(template, n)
if isstring(template)
    values = strings(n, 1);
elseif iscellstr(template)
    values = repmat({''}, n, 1);
elseif islogical(template)
    values = false(n, 1);
else
    values = nan(n, 1);
end
end
