function summary = run_vsg_dc_headroom_direction_scan_20260612(varargin)
%RUN_VSG_DC_HEADROOM_DIRECTION_SCAN_20260612 Short VdcRef direction scan.
%
% This is a direction check only. It starts from the current 1000 V-class
% warm start, so it cannot prove a 1150/1200 V steady operating point.

root = fileparts(mfilename('fullpath'));
oldDir = pwd;
cleanupObj = onCleanup(@() cd(oldDir)); %#ok<NASGU>
cd(root);

p = inputParser;
addParameter(p, 'VdcRefs', [1150 1200]);
addParameter(p, 'NumSegments', 2);
addParameter(p, 'SegmentTime', 1.0);
addParameter(p, 'InitialStateFile', fullfile(root, 'Validation_Results', 'Initial_State', ...
    'Grid_FormingVSG_PMSG_Init_ContinueFrom20s_Vlim280_FF225_Kp0055_Ki00036_20260612_Segment_05.mat'));
parse(p, varargin{:});
cfg = p.Results;

summary = table();
for k = 1:numel(cfg.VdcRefs)
    vref = cfg.VdcRefs(k);
    tag = sprintf('Headroom_Vdc%d_Vlim300_SofterDVC', vref);
    rows = run_vsg_operating_point_segments( ...
        'Tag', tag, ...
        'SegmentTime', cfg.SegmentTime, ...
        'NumSegments', cfg.NumSegments, ...
        'InitialStateFile', cfg.InitialStateFile, ...
        'RunCompile', k == 1, ...
        'DvcType', 3, ...
        'H', 250, ...
        'Mp', 1.5707963e-6, ...
        'MotorFF', 0.000215, ...
        'MotorKp', 0.050, ...
        'MotorKi', 0.00032, ...
        'MotorKc', 1e-5, ...
        'MotorVoltLimit', 300, ...
        'MotorCurrentKp', 1.4, ...
        'MotorCurrentKi', 0.00290476, ...
        'PowerLpfCutoff', 40, ...
        'PrefRampSlope', 5e5, ...
        'DcCapF', 0.03, ...
        'MotorLd', 1.02e-3, ...
        'MotorLq', 1.02e-3, ...
        'Pref_W', 1.0e6, ...
        'Qref_var', 0, ...
        'VacRef_V', 563, ...
        'VdcRef_V', vref);

    last = rows(end,:);
    one = table(vref, string(tag), last.Ppcc_kW, last.Perr_pu, ...
        last.Udc_V, last.UdcSlope, last.UdcMin, last.UdcMax, last.TshSlope, ...
        last.MscIqPiMax, last.MscVcmdMax, last.MscLinearVoltageLimit, ...
        last.MscModDepthMean, last.MscModDepthMax, last.Operational, ...
        last.DcSettled, last.MechSettled, string(last.StateFile), ...
        'VariableNames', {'VdcRef','Tag','Ppcc_kW','Perr_pu', ...
        'Udc_V','UdcSlope','UdcMin','UdcMax','TshSlope', ...
        'MscIqPiMax','MscVcmdMax','MscLinearVoltageLimit', ...
        'MscModDepthMean','MscModDepthMax','Operational', ...
        'DcSettled','MechSettled','StateFile'});
    summary = [summary; one]; %#ok<AGROW>
end

out = fullfile(root, 'Validation_Results', 'vsg_dc_headroom_direction_scan_20260612.csv');
writetable(summary, out);
disp(summary);
fprintf('Saved DC headroom direction scan: %s\n', out);
end
