function rows = run_vsg_operating_point_segments(varargin)
%RUN_VSG_OPERATING_POINT_SEGMENTS Generate VSG warm-start operating points.
%
% 用途：
%   对当前 Grid_FormingVSG_PMSG 模型，先按给定控制参数编译 main_vsg，
%   然后采用分段仿真方式保存每一段末端的 Simulink.op.ModelOperatingPoint。
%
% 为什么不用 StructureWithTime：
%   普通结构状态可以跨编译加载，但对电力电子/Simscape 网络的恢复不如
%   ModelOperatingPoint，已观察到 Udc 轨迹偏离。因此正式热启动仍使用
%   ModelOperatingPoint。
%
% 示例：
%   rows = run_vsg_operating_point_segments('Tag','Default_Op','NumSegments',6);

root = fileparts(mfilename('fullpath'));
oldDir = pwd;
cleanupObj = onCleanup(@() cd(oldDir));
cd(root);

p = inputParser;
addParameter(p, 'Tag', 'Default');
addParameter(p, 'SegmentTime', 1.0);
addParameter(p, 'NumSegments', 6);
addParameter(p, 'InitialStateFile', '');
addParameter(p, 'InitialStateVar', 'xInitial');
addParameter(p, 'RunCompile', true);
addParameter(p, 'DvcType', 3);
addParameter(p, 'H', 250);
addParameter(p, 'Mp', 1.5707963e-6);
addParameter(p, 'MotorFF', 0.000225);
addParameter(p, 'MotorKp', 0.055);
addParameter(p, 'MotorKi', 0.00036);
addParameter(p, 'MotorKc', 1e-5);
addParameter(p, 'MotorVoltLimit', 800);
addParameter(p, 'MotorCurrentKp', []);
addParameter(p, 'MotorCurrentKi', []);
addParameter(p, 'MotorCurrentKc', []);
addParameter(p, 'GridCurrentKp', []);
addParameter(p, 'GridCurrentKi', []);
addParameter(p, 'GridCurrentKc', []);
addParameter(p, 'GridVoltageKp', []);
addParameter(p, 'GridVoltageKi', []);
addParameter(p, 'GridPowerKp', []);
addParameter(p, 'GridPowerKi', []);
addParameter(p, 'PowerLpfCutoff', []);
addParameter(p, 'PrefRampSlope', []);
addParameter(p, 'DcCapF', []);
addParameter(p, 'MotorLd', []);
addParameter(p, 'MotorLq', []);
addParameter(p, 'Pref_W', 1.0e6);
addParameter(p, 'Qref_var', 0);
addParameter(p, 'VacRef_V', 563);
addParameter(p, 'VdcRef_V', 1000);
parse(p, varargin{:});
cfg = p.Results;

if cfg.RunCompile
    compile_vsg_sfunction( ...
        'DvcType', cfg.DvcType, ...
        'VSG_H', cfg.H, ...
        'VSG_MP', cfg.Mp, ...
        'MotorFF', cfg.MotorFF, ...
        'MotorKp', cfg.MotorKp, ...
        'MotorKi', cfg.MotorKi, ...
        'MotorKc', cfg.MotorKc, ...
        'MotorVoltLimit', cfg.MotorVoltLimit, ...
        'MotorCurrentKp', cfg.MotorCurrentKp, ...
        'MotorCurrentKi', cfg.MotorCurrentKi, ...
        'MotorCurrentKc', cfg.MotorCurrentKc, ...
        'GridCurrentKp', cfg.GridCurrentKp, ...
        'GridCurrentKi', cfg.GridCurrentKi, ...
        'GridCurrentKc', cfg.GridCurrentKc, ...
        'GridVoltageKp', cfg.GridVoltageKp, ...
        'GridVoltageKi', cfg.GridVoltageKi, ...
        'GridPowerKp', cfg.GridPowerKp, ...
        'GridPowerKi', cfg.GridPowerKi, ...
        'PowerLpfCutoff', cfg.PowerLpfCutoff, ...
        'PrefRampSlope', cfg.PrefRampSlope, ...
        'DcCapF', cfg.DcCapF, ...
        'MotorLd', cfg.MotorLd, ...
        'MotorLq', cfg.MotorLq);
end

outDir = fullfile(root, 'Validation_Results', 'Initial_State');
if exist(outDir, 'dir') ~= 7
    mkdir(outDir);
end

rows = table();
initFile = char(cfg.InitialStateFile);
for seg = 1:cfg.NumSegments
    overrides = struct( ...
        'ModelName', 'Grid_FormingVSG_PMSG', ...
        'SkipMexCompile', true, ...
        'UseNumericSfunParams', true, ...
        'Pref_W', cfg.Pref_W, ...
        'Qref_var', cfg.Qref_var, ...
        'VacRef_V', cfg.VacRef_V, ...
        'VdcRef_V', cfg.VdcRef_V, ...
        'SaveFinalState', true, ...
        'SaveOperatingPoint', true, ...
        'FinalStateName', 'xInitial', ...
        'SaveSeries', false, ...
        'SeriesMaxPoints', 1000, ...
        'ThreePhaseTail_s', 0.05, ...
        'SimulationMode', 'accelerator');

    if ~isempty(initFile)
        overrides.InitialStateFile = initFile;
        overrides.InitialStateVar = cfg.InitialStateVar;
    end

    d = run_no_disturbance_diagnosis(false, cfg.SegmentTime, 0.0, overrides);
    if ~isfield(d, 'final_state') || isempty(d.final_state)
        error('No final operating point captured at segment %d.', seg);
    end

    xInitial = d.final_state; %#ok<NASGU>
    metadata = cfg; %#ok<NASGU>
    metadata.segment = seg;
    metadata.created = datestr(now);
    metadata.previousFile = initFile;

    safeTag = regexprep(char(cfg.Tag), '[^\w\-]', '_');
    initFile = fullfile(outDir, sprintf('Grid_FormingVSG_PMSG_Init_%s_Segment_%02d.mat', safeTag, seg));
    save(initFile, 'xInitial', 'd', 'metadata', '-v7.3');

    row = table(seg, localSnapshotTime(xInitial), ...
        d.presyn_end_mean, d.Ppcc_end_mean/1e3, d.Ppcc_target_error_pu, ...
        d.udc_end_mean, d.udc_end_slope, d.udc_end_min, d.udc_end_max, ...
        d.T_sh_end_slope, d.omega_g_end_slope, d.omega_t_end_slope, ...
        d.msc_iq_pi_out_end_maxabs, d.msc_vcmd_mag_end_max, ...
        d.msc_linear_voltage_limit, d.msc_mod_depth_mean, d.msc_mod_depth_max, ...
        logical(d.baseline_operational_flag), logical(d.dc_settled_flag), ...
        logical(d.mech_settled_flag), string(d.primary_cause_hint), string(initFile), ...
        'VariableNames', {'Segment','SnapshotTime','PreSyn','Ppcc_kW','Perr_pu', ...
        'Udc_V','UdcSlope','UdcMin','UdcMax','TshSlope','OmegaGSlope','OmegaTSlope', ...
        'MscIqPiMax','MscVcmdMax','MscLinearVoltageLimit','MscModDepthMean','MscModDepthMax', ...
        'Operational','DcSettled','MechSettled','Cause','StateFile'});
    rows = [rows; row]; %#ok<AGROW>

    fprintf(['segment %02d t=%.3f: PreSyn=%.3g, P=%.3f kW, Udc=%.3f, ' ...
        'UdcSlope=%.3f, TshSlope=%.3g, op=%d, mech=%d\n'], ...
        seg, row.SnapshotTime, row.PreSyn, row.Ppcc_kW, row.Udc_V, ...
        row.UdcSlope, row.TshSlope, row.Operational, row.MechSettled);
end

csvPath = fullfile(root, 'Validation_Results', sprintf('vsg_operating_point_segments_%s.csv', safeTag));
writetable(rows, csvPath);
fprintf('Saved segment summary: %s\n', csvPath);
end

function t = localSnapshotTime(xInitial)
if isa(xInitial, 'Simulink.op.ModelOperatingPoint')
    t = xInitial.snapshotTime;
elseif isstruct(xInitial) && isfield(xInitial, 'time') && ~isempty(xInitial.time)
    t = xInitial.time(end);
else
    t = NaN;
end
end
