function diag = run_gfm_with_initial_state(simStop, initStateFile)
% Warm-started no-disturbance run using a saved initial-state snapshot.
% The snapshot should be generated from the same model, not copied from
% another plant/topology.
% The current default is the 1200 V nonlinear baseline. Prefer the
% same-object-aligned operating point when it becomes available.

if nargin < 1 || isempty(simStop)
    simStop = 10.0;
end
if nargin < 2 || isempty(initStateFile)
    initStateFile = fullfile(fileparts(mfilename('fullpath')), ...
        'Validation_Results', 'Initial_State', ...
        'Grid_Forming_PMSG_Init_940V_provisional.mat');
end

if exist(initStateFile, 'file') ~= 2
    error('Initial-state file not found: %s', initStateFile);
end

snapshot = load(initStateFile, 'metadata');
vdcRef = 1200;
if isfield(snapshot, 'metadata') && isfield(snapshot.metadata, 'vdc_reference_V') ...
        && isequal(snapshot.metadata.vdc_reference_V, 1200)
    vdcRef = snapshot.metadata.vdc_reference_V;
end

ctrl = struct( ...
    'VdcRef_V', vdcRef, ...
    'VacRef_V', 563, ...
    'Pref_W', 1e6, ...
    'Qref_var', 0, ...
    'SkipMexCompile', true, ...
    'UseNumericSfunParams', true, ...
    'InitialStateFile', initStateFile, ...
    'InitialStateVar', 'xInitial', ...
    'SaveSeries', true, ...
    'SeriesMaxPoints', 50000, ...
    'ThreePhaseTail_s', 0.2);

diag = run_no_disturbance_diagnosis(false, simStop, 0.0, ctrl);
fprintf('Warm-started run used: %s\n', initStateFile);
fprintf('Warm-started Vdc reference: %.3f V\n', vdcRef);
end
