function names = m0_output_names()
%M0_OUTPUT_NAMES M0诊断输出顺序。
names = [ ...
    "P_MSC_dc_W"; "P_GSC_dc_W"; "P_PCC_W"; "P_Grid_W"; ...
    "Q_PCC_var"; "Udc_V"; "Tgen_Nm"; "Tshaft_Nm"; ...
    "omega_t_radps"; "omega_g_radps"; "omega_rel_radps"; ...
    "omega_vsg_radps"; "delta_v_rad"; "Vpcc_peak_V"; ...
    "If_peak_A"; "Ig_peak_A"; "DC_energy_residual_W"; ...
    "filter_power_balance_residual_W"; "dUdc_Vps"; ...
    "Pmech_W"; "Pairgap_W"; "Vgsc_cmd_peak_V"; ...
    "i_m_d_ref_A"; "i_m_q_ref_A"; "P_f_W"; "Q_f_var"; ...
    "Vref_peak_V"; "dE_filter_dt_W"; "P_filter_loss_W"];
end
