function [pvec,names] = m0_pack_parameters(P,OP)
%M0_PACK_PARAMETERS 将结构参数显式打包给Simulink MATLAB Function块。
names = [ ...
    "Sbase_W"; "Vdc_ref_V"; "omega0_radps"; "Vgrid_peak_V"; ...
    "Rf_ohm"; "Lf_H"; "Cf_F"; "Rd_ohm"; "Rg_ohm"; "Lg_H"; ...
    "Cdc_F"; "omega_m0_radps"; "Rs_ohm"; "Ld_H"; "Lq_H"; ...
    "psi_f_Wb"; "pole_pairs"; "Kt_Nm_per_A"; "Jt_kgm2"; ...
    "Jg_kgm2"; "Ksh_Nm_per_rad"; "Dsh_Nms_per_rad"; ...
    "Dt_Nms_per_rad"; "Dg_Nms_per_rad"; "Kp_dvc_A_per_V"; ...
    "Ki_dvc_A_per_Vs"; "Kp_msc_i_V_per_A"; ...
    "Ki_msc_i_V_per_As"; "Kp_gsc_i_V_per_A"; ...
    "Ki_gsc_i_V_per_As"; "Kp_gsc_v_A_per_V"; ...
    "Ki_gsc_v_A_per_Vs"; "H_s"; "mp_radps_per_W"; ...
    "pq_filter_radps"; "qv_droop_V_per_var"; "Pref_W"; ...
    "Qref_var"; "Tm0_Nm"; "E0_peak_V"; ...
    "vsg_physical_power_error_sign"; ...
    "gsc_grid_current_feedforward"; "gsc_pcc_voltage_feedforward"];
pvec = [ ...
    P.Sbase_W; P.Vdc_ref_V; P.omega0_radps; P.Vphase_peak_V; ...
    P.Rf_ohm; P.Lf_H; P.Cf_F; P.Rd_ohm; P.Rg_ohm; P.Lg_H; ...
    P.Cdc_F; P.omega_m0_radps; P.Rs_ohm; P.Ld_H; P.Lq_H; ...
    P.psi_f_Wb; P.pole_pairs; P.Kt_Nm_per_A; P.Jt_kgm2; ...
    P.Jg_kgm2; P.Ksh_Nm_per_rad; P.Dsh_Nms_per_rad; ...
    P.Dt_Nms_per_rad; P.Dg_Nms_per_rad; P.Kp_dvc_A_per_V; ...
    P.Ki_dvc_A_per_Vs; P.Kp_msc_i_V_per_A; ...
    P.Ki_msc_i_V_per_As; P.Kp_gsc_i_V_per_A; ...
    P.Ki_gsc_i_V_per_As; P.Kp_gsc_v_A_per_V; ...
    P.Ki_gsc_v_A_per_Vs; P.H_s; P.mp_radps_per_W; ...
    P.pq_filter_radps; P.qv_droop_V_per_var; P.Pref_W; ...
    P.Qref_var; OP.Tm0_Nm; OP.E0_peak_V; ...
    P.vsg_physical_power_error_sign; ...
    P.gsc_grid_current_feedforward; P.gsc_pcc_voltage_feedforward];
assert(numel(pvec)==numel(names));
end
