function mexPath = build_s7_legacy_average_mex(forceRebuild)
%BUILD_S7_LEGACY_AVERAGE_MEX
% 为 S7-5C2 Legacy_Average_Plant 构建隔离的 C/S-Function。
%
% 该 MEX 只把遗留控制器在控制事件层的平均电压指令导出给
% Average VSC；生产开关 MEX、原始模型和 M0 模型均不会被覆盖。
% 输出端口 1:37 保持 Legacy 诊断接口，端口 38:41 为：
%   38 motor U_alpha, 39 motor U_beta,
%   40 grid  U_alpha, 41 grid  U_beta。

if nargin < 1
    forceRebuild = false;
end

here = fileparts(mfilename('fullpath'));
srcDir = fullfile(fileparts(here), 'CurrentModel_Idealized');
outDir = fullfile(here, 'temp', 'S7_5_LegacyPlant');
if ~isfolder(outDir)
    mkdir(outDir);
end

mexName = 'main_s7_legacy_avg';
mexPath = fullfile(outDir, [mexName, '.', mexext]);
if isfile(mexPath) && ~forceRebuild
    fprintf('Reuse %s\n', mexPath);
    return;
end

oldDir = pwd;
cleanupDir = onCleanup(@() cd(oldDir)); %#ok<NASGU>
cd(srcDir);
setenv('MW_MINGW64_LOC', 'C:\mingw64');
clear mex;

% 仅改变平均输出接口和控制器调用周期；其余参数与当前 M0 研究基准一致。
defs = { ...
    '-DLEGACY_AD_S_FUNCTION_NAME=main_s7_legacy_avg', ...
    '-DIDEAL_AVG_OUTPUTS=1', ...
    '-DIDEAL_CONTINUOUS_CONTROLLER=0', ...
    '-DLEGACY_SFUNCTION_SAMPLE_TIME_S=5e-5', ...
    '-DLEGACY_TIMER_TICK_US=100.0', ...
    '-DLEGACY_RESET_CONTROLLER_ON_INIT=1', ...
    '-DENABLE_VSG_EQUIV_WREF=1', ...
    '-DGSI_GFL_MODE=0', ...
    '-DVSG_GRID_SYNC_ENABLE=0', ...
    '-DPRESYN_SWITCH_TIME=0', ...
    '-DGSI_GFM_ENABLE_TIME_S=0', ...
    '-DMSC_DVC_ENABLE_TIME_S=0', ...
    '-DMSC_TYPEC_USE_PCC_POWER_FF=0', ...
    '-DMOTOR_MSC_DVC_TYPE=1', ...
    '-DMOTOR_TORSIONAL_AD_ENABLE=0', ...
    '-DMSC_AD_IQ_GAIN=0', ...
    '-DGSI_DC_ENERGY_KP_W_PER_V=0', ...
    '-DGSI_DC_ENERGY_KI_W_PER_VS=0', ...
    '-DGSI_DC_ENERGY_POWER_LIMIT_W=0', ...
    '-DGSI_DC_ENERGY_INTEGRAL_ENABLE_TIME_S=1e9', ...
    '-DGSI_DC_ENERGY_DEADBAND_V=0', ...
    '-DGSI_PREF_RAMP_SLOPE=1e12', ...
    '-DGSI_CURRENT_VECTOR_LIMIT_A=0', ...
    '-DGSI_VOLTAGE_MODULATION_LIMIT=0', ...
    '-DGSI_NORMAL_LIMITS_ENABLE=0', ...
    '-DMSC_LVRT_ENABLE_TIME_S=1e9', ...
    '-DMSC_LVRT_UDC_THRESHOLD_V=1e9', ...
    '-DMSC_LVRT_PCC_VOLTAGE_THRESHOLD_V=0', ...
    '-DMSC_LVRT_IQ_LIMIT_A=0', ...
    '-DMSC_LVRT_MODULATION_LIMIT=0', ...
    '-DMSC_LVRT_VOLTAGE_MODULATION_LIMIT=0', ...
    '-DMOTOR_ID_LIMIT_MAX=1e9', ...
    '-DMOTOR_IQ_LIMIT_MAX=1e9', ...
    '-DMOTOR_ID_REF_SLOPE_LIMIT_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_UP_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_DOWN_MAX=1e12', ...
    '-DMOTOR_PI_ID_OUT_MAX=1e9', '-DMOTOR_PI_ID_OUT_MIN=-1e9', ...
    '-DMOTOR_PI_IQ_OUT_MAX=1e9', '-DMOTOR_PI_IQ_OUT_MIN=-1e9', ...
    '-DMOTOR_PWM_SPEED_PI_OUT_MAX=1e9', ...
    '-DMOTOR_PWM_SPEED_PI_OUT_MIN=-1e9', ...
    '-DCURRENT_PI_ID_OUT_MAX=1e9', '-DCURRENT_PI_ID_OUT_MIN=-1e9', ...
    '-DCURRENT_PI_IQ_OUT_MAX=1e9', '-DCURRENT_PI_IQ_OUT_MIN=-1e9', ...
    '-DMOTOR_RS=0.0005', '-DMOTOR_LD=0.00105', '-DMOTOR_LQ=0.00105', ...
    '-DGRID_FILTER__C=0.000275', '-DGRID_UDC__C=0.3', ...
    '-DVSG_EQUIV_H=3.0', ...
    '-DVSG_EQUIV_MP=1.2566370614e-6', ...
    '-DVSG_EQUIV_SBASE_W=5.0e6', ...
    '-DVSG_EQUIV_W0=314.159265358979'};

mex(defs{:}, '-output', fullfile(outDir, mexName), ...
    fullfile(srcDir, 'main_legacy_ad_base.c'), ...
    fullfile(srcDir, 'svpwm.c'), ...
    fullfile(srcDir, 'motorcontrol_legacy_ad_base.c'), ...
    fullfile(srcDir, 'grid_forming_control.c'));

assert(isfile(mexPath), ...
    'build_s7_legacy_average_mex:BuildFailed', ...
    'Legacy average MEX 未生成：%s', mexPath);
fprintf('Built %s\n', mexPath);
end
