function mexPath = build_s7_legacy_hotstart_mex(forceRebuild, debugPrint)
%BUILD_S7_LEGACY_HOTSTART_MEX
% 构建仅供 S7-C2-R 使用的 Legacy 热启动 MEX。
%
% 与生产 main_legacy_ad、冷启动 main_s7_legacy_avg 完全分开：
% - 源文件来自 temp/S7_5_LegacyPlant/hotstart_src；
% - 第五个 S-Function 参数是显式 32 元素热启动状态向量；
% - 生产 C 源、原始开关 MEX 和 M0 模型均不覆盖。

if nargin < 1 || isempty(forceRebuild), forceRebuild = false; end
if nargin < 2 || isempty(debugPrint), debugPrint = false; end
here = fileparts(mfilename('fullpath'));
srcDir = fullfile(here,'temp','S7_5_LegacyPlant','hotstart_src');
outDir = fullfile(here,'temp','S7_5_LegacyPlant');
if ~isfolder(outDir), mkdir(outDir); end
name = 'main_s7_legacy_hot';
mexPath = fullfile(outDir,[name,'.',mexext]);
if isfile(mexPath) && ~forceRebuild
    fprintf('Reuse %s\n',mexPath);
    return;
end
assert(isfile(fullfile(srcDir,'main_legacy_ad_base.c')), ...
    'Missing isolated hot-start source tree: %s',srcDir);
oldDir = pwd; c = onCleanup(@()cd(oldDir)); %#ok<NASGU>
cd(srcDir);
setenv('MW_MINGW64_LOC','C:\mingw64');
clear mex;
defs = { ...
    '-DLEGACY_AD_S_FUNCTION_NAME=main_s7_legacy_hot', ...
    '-DIDEAL_AVG_OUTPUTS=1', ...
    '-DIDEAL_CONTINUOUS_CONTROLLER=0', ...
    '-DLEGACY_SFUNCTION_SAMPLE_TIME_S=5e-5', ...
    '-DLEGACY_TIMER_TICK_US=100.0', ...
    '-DLEGACY_RESET_CONTROLLER_ON_INIT=1', ...
    '-DLEGACY_HOTSTART_ENABLE=1', ...
    '-DENABLE_VSG_EQUIV_WREF=1', ...
    '-DGSI_GFL_MODE=0', ...
    '-DVSG_GRID_SYNC_ENABLE=0', ...
    '-DPRESYN_SWITCH_TIME=0', ...
    '-DGSI_GFM_ENABLE_TIME_S=0', ...
    '-DMSC_DVC_ENABLE_TIME_S=0', ...
    '-DMSC_TYPEC_USE_PCC_POWER_FF=0', ...
    '-DMOTOR_MSC_DVC_TYPE=1', ...
    '-DMOTOR_TORSIONAL_AD_ENABLE=0', ...
    '-DMSC_AD_IQ_GAIN=0', ...
    '-DGSI_DC_ENERGY_KP_W_PER_V=0', ...
    '-DGSI_DC_ENERGY_KI_W_PER_VS=0', ...
    '-DGSI_DC_ENERGY_POWER_LIMIT_W=0', ...
    '-DGSI_DC_ENERGY_INTEGRAL_ENABLE_TIME_S=1e9', ...
    '-DGSI_DC_ENERGY_DEADBAND_V=0', ...
    '-DGSI_PREF_RAMP_SLOPE=1e12', ...
    '-DGSI_CURRENT_VECTOR_LIMIT_A=0', ...
    '-DGSI_VOLTAGE_MODULATION_LIMIT=0', ...
    '-DGSI_NORMAL_LIMITS_ENABLE=0', ...
    '-DMSC_LVRT_ENABLE_TIME_S=1e9', ...
    '-DMSC_LVRT_UDC_THRESHOLD_V=1e9', ...
    '-DMSC_LVRT_PCC_VOLTAGE_THRESHOLD_V=0', ...
    '-DMSC_LVRT_IQ_LIMIT_A=0', ...
    '-DMSC_LVRT_MODULATION_LIMIT=0', ...
    '-DMSC_LVRT_VOLTAGE_MODULATION_LIMIT=0', ...
    '-DMOTOR_ID_LIMIT_MAX=1e9', '-DMOTOR_IQ_LIMIT_MAX=1e9', ...
    '-DMOTOR_ID_REF_SLOPE_LIMIT_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_UP_MAX=1e12', ...
    '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_DOWN_MAX=1e12', ...
    '-DMOTOR_PI_ID_OUT_MAX=1e9', '-DMOTOR_PI_ID_OUT_MIN=-1e9', ...
    '-DMOTOR_PI_IQ_OUT_MAX=1e9', '-DMOTOR_PI_IQ_OUT_MIN=-1e9', ...
    '-DMOTOR_PWM_SPEED_PI_OUT_MAX=1e9', ...
    '-DMOTOR_PWM_SPEED_PI_OUT_MIN=-1e9', ...
    '-DCURRENT_PI_ID_OUT_MAX=1e9', '-DCURRENT_PI_ID_OUT_MIN=-1e9', ...
    '-DCURRENT_PI_IQ_OUT_MAX=1e9', '-DCURRENT_PI_IQ_OUT_MIN=-1e9', ...
    '-DMOTOR_RS=0.0005', '-DMOTOR_LD=0.00105', '-DMOTOR_LQ=0.00105', ...
    '-DGRID_FILTER__C=0.000275', '-DGRID_UDC__C=0.3', ...
    '-DGSI_NOMINAL_VOLTAGE_PHASE_PEAK_V=556.029701073', ...
    '-DVSG_EQUIV_H=3.0', '-DVSG_EQUIV_MP=1.2566370614e-6', ...
    '-DVSG_EQUIV_SBASE_W=5.0e6', '-DVSG_EQUIV_W0=314.159265358979'};
if debugPrint
    defs{end+1} = '-DLEGACY_HOTSTART_DEBUG_PRINT=1';
end
mex(defs{:},'-output',fullfile(outDir,name), ...
    fullfile(srcDir,'main_legacy_ad_base.c'), ...
    fullfile(srcDir,'svpwm.c'), ...
    fullfile(srcDir,'motorcontrol_legacy_ad_base.c'), ...
    fullfile(srcDir,'grid_forming_control.c'));
assert(isfile(mexPath),'Hot-start MEX build failed: %s',mexPath);
fprintf('Built %s\n',mexPath);
end
