function T = build_same_object_parameter_table()
% Build a same-object parameter table among:
% 1) small-signal Parameters.mat
% 2) nonlinear Simulink/initialization variables
% 3) nonlinear C controllers (current values in headers)

rootDir = fileparts(mfilename('fullpath'));
ssmMat = locate_ssm_parameters_mat();
ssm = load(ssmMat);

% Ensure nonlinear initialization uses the same source MAT when enabled.
run(fullfile(rootDir, 'GFM_MWT_Nonlinear_Params.m'));

% C-side values (current headers; used for mismatch visibility)
c = struct();
c.MOTOR_RS = 0.0122;
c.MOTOR_LD = 0.00102;
c.MOTOR_LQ = 0.00102;
c.MOTOR_POLE_PAIR = 20;
c.GRID_UDC_C = 0.0015;
c.GRID_FILTER_LS = 0.00012;
c.GRID_FILTER_C = 0.000055;
c.GRID_LINE_L = 0.0005;
c.MOTOR_ID_KP = 1.4;
c.MOTOR_ID_KI = 0.00290476;
c.GSC_P_KP = 1e-6;
c.GSC_P_KI = 2e-5;
c.VSG_J = 10;
c.VSG_D = 2000;

names = { ...
    'S_base/P_wt_rated', ...
    'omega_g0/omega_m0', ...
    'v_w0', ...
    'J_t', ...
    'J_g', ...
    'K_sh', ...
    'D_sh', ...
    'D_aero', ...
    'K_v_aero', ...
    'R_s vs MOTOR_RS', ...
    'L_d vs MOTOR_LD', ...
    'L_q vs MOTOR_LQ', ...
    'n_p vs MOTOR_POLE_PAIR', ...
    'C_dc vs GRID_UDC_C', ...
    'lf1 vs GRID_FILTER_LS', ...
    'cf vs GRID_FILTER_C', ...
    'lg vs GRID_LINE_L', ...
    'k_pm vs MOTOR_ID_KP', ...
    'k_im vs MOTOR_ID_KI', ...
    'k_pdc vs GSC_P_KP', ...
    'k_idc vs GSC_P_KI', ...
    'h (VSG inertia) vs VSG_J', ...
    'mp (droop) vs 1/VSG_D (equiv)' ...
    };

ssmVals = [ ...
    getf(ssm,'S_base',NaN), ...
    getf(ssm,'omega_g0',NaN), ...
    getf(ssm,'v_w0',NaN), ...
    getf(ssm,'J_t',NaN), ...
    getf(ssm,'J_g',NaN), ...
    getf(ssm,'K_sh',NaN), ...
    getf(ssm,'D_sh',NaN), ...
    getf(ssm,'D_aero',NaN), ...
    getf(ssm,'K_v_aero',NaN), ...
    getf(ssm,'R_s',NaN), ...
    getf(ssm,'L_d',NaN), ...
    getf(ssm,'L_q',NaN), ...
    getf(ssm,'n_p',NaN), ...
    getf(ssm,'C_dc',NaN), ...
    getf(ssm,'lf1',NaN), ...
    getf(ssm,'cf',NaN), ...
    getf(ssm,'lg',NaN), ...
    getf(ssm,'k_pm',NaN), ...
    getf(ssm,'k_im',NaN), ...
    getf(ssm,'k_pdc',NaN), ...
    getf(ssm,'k_idc',NaN), ...
    getf(ssm,'h',NaN), ...
    getf(ssm,'mp',NaN) ...
    ]';

nonVals = [ ...
    P_wt_rated, ...
    omega_m0, ...
    v_w0, ...
    J_t, ...
    J_g, ...
    K_sh, ...
    D_sh, ...
    D_aero, ...
    K_v_aero, ...
    c.MOTOR_RS, ...
    c.MOTOR_LD, ...
    c.MOTOR_LQ, ...
    c.MOTOR_POLE_PAIR, ...
    c.GRID_UDC_C, ...
    c.GRID_FILTER_LS, ...
    c.GRID_FILTER_C, ...
    c.GRID_LINE_L, ...
    c.MOTOR_ID_KP, ...
    c.MOTOR_ID_KI, ...
    c.GSC_P_KP, ...
    c.GSC_P_KI, ...
    c.VSG_J, ...
    1/max(c.VSG_D, eps) ...
    ]';

ratio = nonVals ./ ssmVals;
ratio(~isfinite(ratio)) = NaN;

T = table(names', ssmVals, nonVals, ratio, 'VariableNames', ...
    {'Parameter', 'SmallSignalValue', 'NonlinearCurrentValue', 'NonlinearOverSmallSignal'});

outDir = fullfile(rootDir, 'Validation_Results');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end
writetable(T, fullfile(outDir, 'same_object_parameter_table.csv'));

% Write a concise report.
md = fullfile(outDir, 'same_object_parameter_table.md');
fid = fopen(md, 'w');
fprintf(fid, '# 同一对象参数对照表\n\n');
fprintf(fid, '- Small-signal source: `%s`\n', ssmMat);
fprintf(fid, '- Nonlinear init script: `GFM_MWT_Nonlinear_Params.m`\n');
fprintf(fid, '- Nonlinear C control headers: `motorcontrol.h`, `grid_forming_control.h`\n\n');
fprintf(fid, '| Parameter | Small-signal | Nonlinear | Ratio (non/ss) |\n');
fprintf(fid, '|---|---:|---:|---:|\n');
for i = 1:height(T)
    fprintf(fid, '| %s | %.6g | %.6g | %.6g |\n', ...
        T.Parameter{i}, T.SmallSignalValue(i), T.NonlinearCurrentValue(i), T.NonlinearOverSmallSignal(i));
end

fprintf(fid, '\n## 控制结构差异（当前）\n');
fprintf(fid, '- 小信号主模型以 `h/mp` 对应的 VSG/下垂参数进行模态分析。\n');
fprintf(fid, '- 非线性当前为 `P环->w_ref` 与 `Q下垂->E` 的实现，尚未完全等价于二阶 VSG 摆动方程。\n');
fprintf(fid, '- 建议后续在 C 侧补齐等价状态环节：`2H*w0*dw/dt = P_ref - P - D*(w-w0)`，保证与小信号严格一致。\n');
fclose(fid);

disp(T);
fprintf('Saved: %s\n', fullfile(outDir, 'same_object_parameter_table.csv'));
fprintf('Saved: %s\n', md);
end

function v = getf(s, name, fallback)
if isfield(s, name)
    v = s.(name);
else
    v = fallback;
end
end

