function mexPath = build_idealized_controller_mex()
% 编译当前模型理想化副本专用控制器。
% 与原始开关模型分离：不覆盖原MEX、不改原模型。
here=fileparts(mfilename('fullpath'));
old=pwd; c=onCleanup(@()cd(old)); cd(here);
setenv('MW_MINGW64_LOC','C:\mingw64');
clear mex;
name='main_5mw_idealized';
defs={...
 '-DLEGACY_AD_S_FUNCTION_NAME=main_5mw_idealized', ...
 '-DIDEAL_AVG_OUTPUTS=1', ...
 '-DIDEAL_CONTINUOUS_CONTROLLER=1', ...
 '-DLEGACY_SFUNCTION_SAMPLE_TIME_S=4e-6', ...
 '-DLEGACY_RUNTIME_DVC_SCALE=1', ...
 '-DLEGACY_RESET_CONTROLLER_ON_INIT=1', ...
 '-DENABLE_VSG_EQUIV_WREF=1', ...
 '-DVSG_POWER_ERROR_SIGN=1', ... % M0物理相对角约定；最终仍需通过 dP/delta>0 验收
 '-DVSG_EQUIV_H=3.0', '-DVSG_EQUIV_MP=1.2566370614e-6', ...
 '-DVSG_EQUIV_SBASE_W=5.0e6', '-DVSG_EQUIV_W0=314.159265358979', ...
 '-DGRID_FILTER__LS=4.54642e-5', '-DGRID_FILTER__C=2.75e-4', '-DGRID_UDC__C=0.3', ...
 '-DCURRENT_LOOP_BANDWITH=300', ...
 '-DCURRENT_ID_KP=0.085698', '-DCURRENT_IQ_KP=0.085698', ...
 '-DCURRENT_ID_KI=4.19e-5', '-DCURRENT_IQ_KI=4.19e-5', ...
 '-DGSI_V_LOOP_KP=0.0933053018', '-DGSI_V_LOOP_KI=4.19e-4', ...
 '-DGSI_VOLTAGE_GRID_CURRENT_FF_SIGN=1.0', ... % 端口电流前馈方向，需由功率符号测试最终确认
 '-DVSG_GRID_SYNC_ENABLE=0', ...
 '-DPRESYN_SWITCH_TIME=0', ...
 '-DGSI_GFM_ENABLE_TIME_S=0', ...
 '-DMSC_DVC_ENABLE_TIME_S=0', ...
 '-DMOTOR_ID_KP=1.4', '-DMOTOR_IQ_KP=1.4', ...
 '-DMOTOR_ID_KI=1.161904e-4', '-DMOTOR_IQ_KI=1.161904e-4', ...
 '-DMOTOR_PWM_SPEED_KP=0.05', '-DMOTOR_PWM_SPEED_KI=2.0e-5', ...
 '-DMSC_TYPEC_USE_PCC_POWER_FF=0', ...
 '-DMOTOR_MSC_DVC_TYPE=1', ...
 '-DMOTOR_TORSIONAL_AD_ENABLE=0', ...
 '-DMSC_AD_IQ_GAIN=0', ...
 '-DMSC_AD_IQ_LIMIT=0', ...
 '-DGSI_DC_ENERGY_KP_W_PER_V=0', ...
 '-DGSI_DC_ENERGY_KI_W_PER_VS=0', ...
 '-DGSI_DC_ENERGY_POWER_LIMIT_W=0', ...
 '-DGSI_DC_ENERGY_INTEGRAL_ENABLE_TIME_S=1e9', ...
 '-DGSI_DC_ENERGY_DEADBAND_V=0', ...
 '-DGSI_PREF_RAMP_SLOPE=1e12', ...
 '-DGSI_CURRENT_VECTOR_LIMIT_A=0', ...
 '-DGSI_VOLTAGE_MODULATION_LIMIT=0', ...
 '-DGSI_NORMAL_LIMITS_ENABLE=0', ...
 '-DMSC_LVRT_ENABLE_TIME_S=1e9', ...
 '-DMSC_LVRT_UDC_THRESHOLD_V=1e9', ...
 '-DMSC_LVRT_PCC_VOLTAGE_THRESHOLD_V=0', ...
 '-DMSC_LVRT_IQ_LIMIT_A=0', ...
 '-DMSC_LVRT_MODULATION_LIMIT=0', ...
 '-DMSC_LVRT_VOLTAGE_MODULATION_LIMIT=0', ...
 '-DMOTOR_ID_LIMIT_MAX=1e9', ...
 '-DMOTOR_IQ_LIMIT_MAX=1e9', ...
 '-DMOTOR_ID_REF_SLOPE_LIMIT_MAX=1e12', ...
 '-DMOTOR_IQ_REF_SLOPE_LIMIT_MAX=1e12', ...
 '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_MAX=1e12', ...
 '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_UP_MAX=1e12', ...
 '-DMOTOR_IQ_REF_SLOPE_LIMIT_STEADY_DOWN_MAX=1e12', ...
 '-DMOTOR_PI_ID_OUT_MAX=1e9', '-DMOTOR_PI_ID_OUT_MIN=-1e9', ...
 '-DMOTOR_PI_IQ_OUT_MAX=1e9', '-DMOTOR_PI_IQ_OUT_MIN=-1e9', ...
 '-DMOTOR_PWM_SPEED_PI_OUT_MAX=1e9', '-DMOTOR_PWM_SPEED_PI_OUT_MIN=-1e9', ...
 '-DCURRENT_PI_ID_OUT_MAX=1e9', '-DCURRENT_PI_ID_OUT_MIN=-1e9', ...
 '-DCURRENT_PI_IQ_OUT_MAX=1e9', '-DCURRENT_PI_IQ_OUT_MIN=-1e9'};
% 5 MW实际参数优先于头文件旧默认值。
defs=[defs,{'-DMOTOR_RS=0.0005','-DMOTOR_LD=0.00105','-DMOTOR_LQ=0.00105','-DGRID_FILTER__C=0.000275','-DGRID_UDC__C=0.3'}];
mex(defs{:},'-output',name,'main_legacy_ad_base.c','svpwm.c','motorcontrol_legacy_ad_base.c','grid_forming_control.c');
mexPath=fullfile(here,[name,'.',mexext]);
assert(exist(mexPath,'file')==3,'理想化控制器MEX未生成');
fprintf('Built %s\n',mexPath);
end
