function J = solve_joint_physical_periodic_operating_point()
%SOLVE_JOINT_PHYSICAL_PERIODIC_OPERATING_POINT
% Build the one t=0 operating state shared by the retained SPS RC-LCL
% network, ideal GSC voltage source and explicit continuous GSC/VSG states.
% The function writes no files and does not save the model.

here=fileparts(mfilename('fullpath'));
mdl='Grid_Forming_PMSG5MW_TwoMass_Idealized';
OPa=solve_currentmodel_source_aligned_equilibrium();
P=init_m0_5mw_parameters();
load_system(fullfile(here,[mdl '.slx']));
% 直接点击 Run 时模型会自动加载已验收的 xInitial；但本函数自身正是
% 用来重新求解该工作点的，不能让旧外部初态参与编译。此外
% BlockDiagram.getInitialState 不支持 Accelerator 模式，因此在本次
% 内存求解期间强制使用 normal/off，模型文件本身的设置不被保存。
set_param(mdl,'SimulationMode','normal','LoadInitialState','off');
set_param(mdl,'SimulationCommand','update');

% Read the exact continuous network realization generated by powergui.
eq=[mdl '/powergui/EquivalentModel2'];
mw=get_param(eq,'MaskWSVariables');
outer=mw(strcmp({mw.Name},'S')).Value;
N=outer.S;
assert(outer.nb.x==9 && numel(N.IndependentStates)==7 && ...
    numel(N.TotalStates)==9, ...
    'Unexpected SPS network state dimension; re-audit the retained topology.');

% powergui uses the sine-phasor convention u(t)=imag(U*exp(j*w*t)).
% For theta_grid=w*t-pi/2, a grid-dq vector [d;q] maps to the phase-A
% phasor d+j*q. The retained source terminal orientation and the audited
% CmdPolarity=-1 require the negative terminal-voltage phasor at the SPS
% controlled-source input.
w=P.omega0_radps;
positiveSequence=[1;exp(-1i*2*pi/3);exp(1i*2*pi/3)];
Ugrid=N.uss(4:6,2);
opts=optimoptions('fsolve','Display','off','FunctionTolerance',1e-12, ...
    'StepTolerance',1e-12,'OptimalityTolerance',1e-12,'MaxIterations',200);
z0=OPa.uinv_grid_dq_V(:);
[zv,~,exitflag]=fsolve(@powerResidual,z0,opts);
assert(exitflag>0,'Exact SPS P/Q equilibrium solve failed.');
z=zv(1)+1i*zv(2);
Ugsc=-z*positiveSequence;
U=[Ugsc;Ugrid];
X=(1i*w*eye(size(N.A))-N.A)\(N.B*U);
phasorResidual=(1i*w*eye(size(N.A))-N.A)*X-N.B*U;
Y=N.C*X+N.D*U;

% Recover the exact physical measurement planes from the SPS outputs.
Vll=Y(1:3);
Vp=[(Vll(1)-Vll(3))/3; (Vll(2)-Vll(1))/3; (Vll(3)-Vll(2))/3];
If=[Y(4);Y(6);Y(7)];
Ig=[Y(5);Y(8);Y(9)];
S_pcc=0.5*sum(Vp.*conj(Ig));
Pgsc=0.5*real(sum(Ugsc.*conj(Y(10:12))));
delta=angle(Vp(1));
vLocal=Vp(1)*exp(-1i*delta);
iFLocal=If(1)*exp(-1i*delta);
iGLocal=Ig(1)*exp(-1i*delta);
uLocal=z*exp(-1i*delta);

% The two retained ideal-source interface subsystems use a very fast
% first-order continuous regularizer (A=-1e7,B=1e7) solely to make the SPS
% direct-feedthrough interconnection numerically well posed.  It is not a
% controller delay.  A sinusoidal equilibrium must therefore initialize
% the regularizer on its periodic orbit and pre-compensate its tiny complex
% gain in the controller command; setting x(0)=u(0) alone is not a periodic
% initial condition and creates the apparent 5--10 ms power drift.
aReg=-1e7; bReg=1e7;
Hg=bReg/(1i*w-aReg);
uRawLocal=(z/Hg)*exp(-1i*delta);

% Close DC-link and mechanical power at the same physical GSC port.
we=P.pole_pairs*P.omega_m0_radps;
powerMsc=@(iq)1.5*(we*P.psi_f_Wb*iq+P.Rs_ohm*iq.^2);
iqGuess=Pgsc/(1.5*we*P.psi_f_Wb);
iq=fzero(@(q)powerMsc(q)-Pgsc,[max(1,0.25*iqGuess),4*iqGuess]);
Pmsc=powerMsc(iq);
Tgen=P.Kt_Nm_per_A*iq;
Hm=bReg/(1i*we-aReg);
vMscDesired=-we*P.Lq_H*iq + 1i*(P.Rs_ohm*iq+we*P.psi_f_Wb);
vMscRaw=vMscDesired/Hm;

ctrl=zeros(11,1);
ctrl(1)=iq;
ctrl(2)=real(vMscRaw)+we*P.Lq_H*iq;
ctrl(3)=imag(vMscRaw)-P.Rs_ohm*iq-we*P.psi_f_Wb;
ctrl(4)=real(S_pcc); ctrl(5)=imag(S_pcc);
ctrl(6)=w; ctrl(7)=delta;
ctrl(8)=real(iFLocal)-P.gsc_grid_current_feedforward*real(iGLocal);
ctrl(9)=imag(iFLocal)-P.Cf_F*w*real(vLocal)- ...
    P.gsc_grid_current_feedforward*imag(iGLocal);
ctrl(10)=real(uRawLocal)+w*P.Lf_H*imag(iFLocal)- ...
    P.gsc_pcc_voltage_feedforward*(real(vLocal)+P.Rf_ohm*real(iFLocal));
ctrl(11)=imag(uRawLocal)-w*P.Lf_H*real(iFLocal)- ...
    P.gsc_pcc_voltage_feedforward*(imag(vLocal)+P.Rf_ohm*imag(iFLocal));
[pvec,pnames]=m0_pack_parameters(P,struct( ...
    'Tm0_Nm',Tgen,'E0_peak_V',abs(Vp(1))));

OP=struct('controller_x0',ctrl,'pmsg_id0',0,'pmsg_iq0',iq, ...
    'theta_tw0',Tgen/P.Ksh_Nm_per_rad,'omega0',P.omega_m0_radps, ...
    'Tgen_Nm',Tgen,'Taero_Nm',Tgen,'P_msc_W',Pmsc,'P_gsc_W',Pgsc, ...
    'P_pcc_measurement_W',real(S_pcc), ...
    'Q_pcc_measurement_var',imag(S_pcc),'delta_vsg_rad',delta, ...
    'vnode_grid_dq_V',[real(Vp(1));imag(Vp(1))], ...
    'vcap_grid_dq_V',[real(X(5));imag(X(5))], ...
    'if_grid_dq_A',[real(If(1));imag(If(1))], ...
    'ig_grid_dq_A',[real(Ig(1));imag(Ig(1))], ...
    'uinv_grid_dq_V',zv(:), ...
    'vmsc_generator_dq_V',[real(vMscDesired);imag(vMscDesired)], ...
    'vmsc_controller_raw_dq_V',[real(vMscRaw);imag(vMscRaw)], ...
    'vgsc_controller_raw_dq_V',[real(uRawLocal);imag(uRawLocal)], ...
    'pvec',pvec(:),'parameter_names',{pnames}, ...
    'energy_residual_W',Pmsc-Pgsc,'torque_residual_Nm',0, ...
    'grid_solver_exitflag',exitflag);

% Reconstruct the two dependent inductor states.  The SPID state order is
% [dependent(2); independent(7)], exactly matching the nine repeated
% State-Space rows returned by power_init for this topology.
M=N.MatStateDependency;
dependent=-(M(:,8:9))\(M(:,1:7)*X);
xSpid=imag([dependent;X]);

% Use a path-addressed Dataset, not a flat numeric array.  powergui groups
% its nine SPID states into one vector block state; a flat array can be
% interpreted in a different compiled order after diagnostic blocks are
% inserted, which corrupts the mechanical initial states.
oldSaveFormat=get_param(mdl,'SaveFormat');
set_param(mdl,'SaveFormat','Dataset');
x0=Simulink.BlockDiagram.getInitialState(mdl);
set_param(mdl,'SaveFormat',oldSaveFormat);
setOne('powergui/EquivalentModel2/State-Space',xSpid(:).');
setOne('Ideal_GSC_AverageVSC/CmdAlphaDelay1',OP.uinv_grid_dq_V(2));
setOne('Ideal_GSC_AverageVSC/CmdBetaDelay1',-OP.uinv_grid_dq_V(1));
setOne('Ideal_MSC_AverageVSC/CmdAlphaDelay1',OP.vmsc_generator_dq_V(1));
setOne('Ideal_MSC_AverageVSC/CmdBetaDelay1',OP.vmsc_generator_dq_V(2));
setOne('PMSM1/elemodel3/iq,id/id/Discrete-Time Integrator',OP.pmsg_id0);
setOne('PMSM1/elemodel3/iq,id/iq/Discrete-Time Integrator',OP.pmsg_iq0);
setOne('Ideal_DC_UdcState',OP.pvec(2));
setOne('Drivetrain_TwoMass/omega_g_state',OP.omega0);
setOne('Drivetrain_TwoMass/omega_t_state',OP.omega0);
setOne('Drivetrain_TwoMass/theta_tw_state',OP.theta_tw0);
for k=1:11
    setOne(sprintf('MOTOR_CONTROL1/IdealCtrlInt%02d',k),OP.controller_x0(k));
end

J=struct();
J.model=mdl;
J.x0=x0;
J.state_names=cell(x0.numElements,1);
for k=1:x0.numElements
    J.state_names{k}=x0{k}.BlockPath.getBlock(1);
end
J.source_aligned=OP;
J.sps_independent_phasor=X;
J.sps_dependent_phasor=dependent;
J.sps_source_phasor=U;
J.sps_output_phasor=Y;
J.sps_initial_state=xSpid;
J.phasor_residual_norm=norm(phasorResidual,inf);
J.gsc_source_power_W=0.5*real(sum(Ugsc.*conj(Y(10:12))));
J.pvec=OP.pvec;
close_system(mdl,0);

    function r=powerResidual(v)
        zz=v(1)+1i*v(2);
        uu=[-zz*positiveSequence;Ugrid];
        xx=(1i*w*eye(size(N.A))-N.A)\(N.B*uu);
        yy=N.C*xx+N.D*uu;
        vl=yy(1:3);
        vp=[(vl(1)-vl(3))/3;(vl(2)-vl(1))/3;(vl(3)-vl(2))/3];
        ig=[yy(5);yy(8);yy(9)];
        ss=0.5*sum(vp.*conj(ig));
        r=([real(ss);imag(ss)]-[P.Pref_W;P.Qref_var])/P.Sbase_W;
    end

    function setOne(suffix,value)
        idx=[];
        for ii=1:x0.numElements
            e=x0{ii};
            bp=e.BlockPath.getBlock(1);
            if endsWith(bp,suffix)
                idx=ii;
                break
            end
        end
        assert(~isempty(idx),'State mapping failed for %s.',suffix);
        e=x0{idx};
        assert(numel(e.Values.Data)==numel(value), ...
            'State width mismatch for %s.',suffix);
        e.Values.Data=reshape(value,size(e.Values.Data));
        x0=x0.setElement(idx,e);
    end
end
