function mexPath = compile_main_legacy_ad(iqGain,iqLimit,prefSlope,presynTime,sfunName,currentLimit,energyKp,energyLimit,energyTarget,energyKi,energyIntegralEnableTime,dvcKp,dvcKi,dvcKc,mscPowerFf,dvcEnableTime,dvcNonnegativeIntegral,currentPiFreezeUntilDvc,motorVoltagePositiveLimit,motorVoltageNegativeLimit,energyDeadband,prefDisturbStart,prefDisturbEnd,prefDisturbDelta,lvrtUdcThreshold,lvrtBlendRange,lvrtMinPower,gscCurrentVectorLimit,gscModulationLimit,lvrtEnableTime,mscLvrtIqLimit,mscLvrtModulationLimit,mscLvrtUdcPowerGain,lvrtPccVoltageThreshold,mscVectorAwGain,gscCurrentRefAwGain,gscVoltageAwGain,gscLvrtActiveCurrentPriority,dcEnergyLvrtOnly,gscLvrtFreezeCurrentPi,mscLvrtFreezeCurrentPi,plantOverrides,varargin_gsc_source)
%COMPILE_MAIN_LEGACY_AD Build the reproducible legacy controller with an
% MSC q-current damping term driven by omega_t-omega_g.

if nargin < 1, iqGain = 317; end       % A/(rad/s), about 4*D_sh/Kt
if nargin < 2, iqLimit = 50; end       % A
if nargin < 3, prefSlope = 1.0e6; end  % W/s
if nargin < 4, presynTime = 1.75; end  % s
if nargin < 5, sfunName = 'main_legacy_ad'; end
if nargin < 6, currentLimit = 1500; end
if nargin < 7, energyKp = 0; end
if nargin < 8, energyLimit = 0; end
if nargin < 9, energyTarget = 1000; end
if nargin < 10, energyKi = 0; end
if nargin < 11, energyIntegralEnableTime = 6.0; end
if nargin < 12, dvcKp = 0.05; end
if nargin < 13, dvcKi = 0.0005; end
if nargin < 14, dvcKc = 0.00001; end
if nargin < 15, mscPowerFf = 0; end
if nargin < 16, dvcEnableTime = presynTime + 1.0; end
if nargin < 17, dvcNonnegativeIntegral = 0; end
if nargin < 18, currentPiFreezeUntilDvc = 0; end
if nargin < 19, motorVoltagePositiveLimit = 700; end
if nargin < 20, motorVoltageNegativeLimit = motorVoltagePositiveLimit; end
if nargin < 21, energyDeadband = 0; end
if nargin < 22, prefDisturbStart = 1e9; end
if nargin < 23, prefDisturbEnd = 1e9; end
if nargin < 24, prefDisturbDelta = 0; end
if nargin < 25, lvrtUdcThreshold = 1e9; end
if nargin < 26, lvrtBlendRange = 1; end
if nargin < 27, lvrtMinPower = 0; end
if nargin < 28, gscCurrentVectorLimit = 0; end
if nargin < 29, gscModulationLimit = 0; end
if nargin < 30, lvrtEnableTime = 0; end
if nargin < 31, mscLvrtIqLimit = 0; end
if nargin < 32, mscLvrtModulationLimit = 0; end
if nargin < 33, mscLvrtUdcPowerGain = 0; end
if nargin < 34, lvrtPccVoltageThreshold = 0; end
if nargin < 35, mscVectorAwGain = 0; end
if nargin < 36, gscCurrentRefAwGain = 0; end
if nargin < 37, gscVoltageAwGain = 0; end
if nargin < 38, gscLvrtActiveCurrentPriority = 0; end
if nargin < 39, dcEnergyLvrtOnly = 0; end
if nargin < 40, gscLvrtFreezeCurrentPi = 0; end
if nargin < 41, mscLvrtFreezeCurrentPi = 0; end
if nargin < 42, plantOverrides = struct(); end
if nargin < 43 || isempty(varargin_gsc_source), varargin_gsc_source = 'grid_forming_control_legacy_rebuild.c'; end
root = fileparts(mfilename('fullpath'));
oldFolder = pwd;
cleanupObj = onCleanup(@() cd(oldFolder)); %#ok<NASGU>
cd(root);
frozenBefore = dir(fullfile(root, ['main.' mexext]));
assert(~isempty(frozenBefore), 'Frozen main MEX is missing.');
setenv('MW_MINGW64_LOC', 'C:\mingw64');
clear(sfunName);
extraDefines = cell(1, 0);
overrideNames = fieldnames(plantOverrides);
for overrideIndex = 1:numel(overrideNames)
    overrideValue = plantOverrides.(overrideNames{overrideIndex});
    assert(isnumeric(overrideValue) && isscalar(overrideValue) && isfinite(overrideValue), ...
        'Plant override %s must be a finite numeric scalar.', overrideNames{overrideIndex});
    extraDefines{end+1} = sprintf('-D%s=%.17g', ...
        overrideNames{overrideIndex}, overrideValue); %#ok<AGROW>
end
mex(sprintf('-DMSC_AD_IQ_GAIN=%.17g',iqGain), ...
    sprintf('-DMSC_AD_IQ_LIMIT=%.17g',iqLimit), ...
    sprintf('-DGSI_PREF_RAMP_SLOPE=%.17g',prefSlope), ...
    sprintf('-DPRESYN_SWITCH_TIME=%.17g',presynTime), ...
    sprintf('-DMOTOR_IQ_LIMIT_MAX=%.17g',currentLimit), ...
    sprintf('-DMOTOR_PWM_SPEED_KP=%.17g',dvcKp), ...
    sprintf('-DMOTOR_PWM_SPEED_KI=%.17g',dvcKi), ...
    sprintf('-DMOTOR_PWM_SPEED_KC=%.17g',dvcKc), ...
    sprintf('-DMOTOR_PI_ID_OUT_MAX=%.17g',motorVoltagePositiveLimit), ...
    sprintf('-DMOTOR_PI_ID_OUT_MIN=%.17g',-motorVoltageNegativeLimit), ...
    sprintf('-DMOTOR_PI_IQ_OUT_MAX=%.17g',motorVoltagePositiveLimit), ...
    sprintf('-DMOTOR_PI_IQ_OUT_MIN=%.17g',-motorVoltageNegativeLimit), ...
    sprintf('-DMSC_POWER_FF_A_PER_W=%.17g',mscPowerFf), ...
    sprintf('-DMSC_DVC_ENABLE_TIME_S=%.17g',dvcEnableTime), ...
    sprintf('-DMSC_DVC_NONNEGATIVE_INTEGRAL=%d', ...
        logical(dvcNonnegativeIntegral)), ...
    sprintf('-DMSC_CURRENT_PI_FREEZE_UNTIL_DVC=%d', ...
        logical(currentPiFreezeUntilDvc)), ...
    sprintf('-DGSI_DC_ENERGY_KP_W_PER_V=%.17g',energyKp), ...
    sprintf('-DGSI_DC_ENERGY_KI_W_PER_VS=%.17g',energyKi), ...
    sprintf('-DGSI_DC_ENERGY_POWER_LIMIT_W=%.17g',energyLimit), ...
    sprintf('-DGSI_DC_ENERGY_TARGET_V=%.17g',energyTarget), ...
    sprintf('-DGSI_DC_ENERGY_INTEGRAL_ENABLE_TIME_S=%.17g',energyIntegralEnableTime), ...
    sprintf('-DGSI_DC_ENERGY_DEADBAND_V=%.17g',energyDeadband), ...
    sprintf('-DGSI_DC_ENERGY_LVRT_ONLY=%d',logical(dcEnergyLvrtOnly)), ...
    sprintf('-DGSI_PREF_DISTURBANCE_START_S=%.17g',prefDisturbStart), ...
    sprintf('-DGSI_PREF_DISTURBANCE_END_S=%.17g',prefDisturbEnd), ...
    sprintf('-DGSI_PREF_DISTURBANCE_DELTA_W=%.17g',prefDisturbDelta), ...
    sprintf('-DMSC_LVRT_UDC_THRESHOLD_V=%.17g',lvrtUdcThreshold), ...
    sprintf('-DMSC_LVRT_BLEND_RANGE_V=%.17g',lvrtBlendRange), ...
    sprintf('-DMSC_LVRT_MIN_POWER_W=%.17g',lvrtMinPower), ...
    sprintf('-DGSI_CURRENT_VECTOR_LIMIT_A=%.17g',gscCurrentVectorLimit), ...
    sprintf('-DGSI_VOLTAGE_MODULATION_LIMIT=%.17g',gscModulationLimit), ...
    sprintf('-DMSC_LVRT_ENABLE_TIME_S=%.17g',lvrtEnableTime), ...
    sprintf('-DMSC_LVRT_IQ_LIMIT_A=%.17g',mscLvrtIqLimit), ...
    sprintf('-DMSC_LVRT_VOLTAGE_MODULATION_LIMIT=%.17g',mscLvrtModulationLimit), ...
    sprintf('-DMSC_LVRT_UDC_POWER_GAIN_W_PER_V=%.17g',mscLvrtUdcPowerGain), ...
    sprintf('-DMSC_LVRT_PCC_VOLTAGE_THRESHOLD_V=%.17g',lvrtPccVoltageThreshold), ...
    sprintf('-DMSC_LVRT_VECTOR_AW_GAIN=%.17g',mscVectorAwGain), ...
    sprintf('-DMSC_LVRT_FREEZE_CURRENT_PI_INTEGRAL=%d', ...
        logical(mscLvrtFreezeCurrentPi)), ...
    sprintf('-DGSI_LVRT_CURRENT_REF_AW_GAIN=%.17g',gscCurrentRefAwGain), ...
    sprintf('-DGSI_LVRT_VOLTAGE_AW_GAIN=%.17g',gscVoltageAwGain), ...
    sprintf('-DGSI_LVRT_ACTIVE_CURRENT_PRIORITY=%d', ...
        logical(gscLvrtActiveCurrentPriority)), ...
    sprintf('-DGSI_LVRT_FREEZE_CURRENT_PI_INTEGRAL=%d', ...
        logical(gscLvrtFreezeCurrentPi)), ...
    extraDefines{:}, ...
    ['-DLEGACY_AD_S_FUNCTION_NAME=' sfunName], ...
    '-output', sfunName, ...
    'main_legacy_ad_base.c', 'svpwm_legacy_rebuild.c', ...
    'motorcontrol_legacy_ad_base.c', varargin_gsc_source);
mexPath = fullfile(root, [sfunName '.' mexext]);
assert(exist(mexPath, 'file') == 3, 'Legacy active-damping MEX was not created.');
frozenAfter = dir(fullfile(root, ['main.' mexext]));
assert(frozenAfter.bytes == frozenBefore.bytes && ...
    frozenAfter.datenum == frozenBefore.datenum, ...
    'Frozen main MEX changed during active-damping build.');
manifest = table(string(sfunName), iqGain, iqLimit, prefSlope, presynTime, ...
    currentLimit, energyKp, energyKi, energyLimit, energyTarget, ...
    energyIntegralEnableTime, dvcKp, dvcKi, dvcKc, mscPowerFf, ...
    dvcEnableTime, logical(dvcNonnegativeIntegral), ...
    logical(currentPiFreezeUntilDvc), motorVoltagePositiveLimit, ...
    motorVoltageNegativeLimit, energyDeadband, prefDisturbStart, ...
    prefDisturbEnd, prefDisturbDelta, lvrtUdcThreshold, ...
    lvrtBlendRange, lvrtMinPower, gscCurrentVectorLimit, ...
    gscModulationLimit, lvrtEnableTime, mscLvrtIqLimit, ...
    mscLvrtModulationLimit, mscLvrtUdcPowerGain, ...
    lvrtPccVoltageThreshold, mscVectorAwGain, ...
    gscCurrentRefAwGain, gscVoltageAwGain, ...
    logical(gscLvrtActiveCurrentPriority), ...
    logical(dcEnergyLvrtOnly), ...
    logical(gscLvrtFreezeCurrentPi), ...
    logical(mscLvrtFreezeCurrentPi), ...
    string(datetime('now','Format','yyyy-MM-dd HH:mm:ss')), ...
    'VariableNames', {'SFunction','MscAdIqGain_A_per_radps', ...
    'MscAdIqLimit_A','PrefRamp_W_per_s','PresyncTime_s', ...
    'MscIqLimit_A','DcEnergyKp_W_per_V','DcEnergyKi_W_per_Vs', ...
    'DcEnergyLimit_W','DcEnergyTarget_V','DcIntegralEnableTime_s', ...
    'MscDvcKp','MscDvcKi','MscDvcKc','MscPowerFf_A_per_W', ...
    'MscDvcEnableTime_s','MscDvcNonnegativeIntegral', ...
    'MscCurrentPiFreezeUntilDvc','MotorVoltagePositiveLimit_V', ...
    'MotorVoltageNegativeLimit_V','DcEnergyDeadband_V', ...
    'PrefDisturbanceStart_s','PrefDisturbanceEnd_s', ...
    'PrefDisturbanceDelta_W','LvrtUdcThreshold_V', ...
    'LvrtBlendRange_V','LvrtMinPower_W','GscCurrentVectorLimit_A', ...
    'GscModulationLimit','LvrtEnableTime_s','MscLvrtIqLimit_A', ...
    'MscLvrtModulationLimit','MscLvrtUdcPowerGain_W_per_V', ...
    'LvrtPccVoltageThreshold_V','MscVectorAwGain', ...
    'GscCurrentRefAwGain','GscVoltageAwGain', ...
    'GscLvrtActiveCurrentPriority','DcEnergyLvrtOnly', ...
    'GscLvrtFreezeCurrentPi','MscLvrtFreezeCurrentPi','BuildTime'});
writetable(manifest, fullfile(root, [sfunName '_build_manifest.csv']));
fprintf(['Built legacy MSC damping controller: %s\n' ...
     'Iq gain %.9g A/(rad/s), AD limit %.9g A, Pref slope %.9g W/s, Iq limit %.9g A\n' ...
     'DC-energy Kp %.9g W/V, Ki %.9g W/(V*s), limit %.9g W, target %.9g V, integral enable %.9g s, deadband %.9g V\n' ...
     'MSC-DVC Kp %.9g, Ki %.9g, Kc %.9g, power FF %.9g A/W, enable %.9g s, nonnegative integral %d, current-PI startup freeze %d, voltage limits [-%.9g,+%.9g] V\n'], ...
    mexPath,iqGain,iqLimit,prefSlope,currentLimit,energyKp,energyKi, ...
    energyLimit,energyTarget,energyIntegralEnableTime,energyDeadband,dvcKp,dvcKi,dvcKc, ...
    mscPowerFf,dvcEnableTime,logical(dvcNonnegativeIntegral), ...
    logical(currentPiFreezeUntilDvc),motorVoltageNegativeLimit, ...
    motorVoltagePositiveLimit);
end
